### ISSUE TITLE
evil-surround-change does not work with backticks

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil-surround#102]
steps to reproduce:

[|] = cursor

```elisp
`this_is_a_[b]acktick_surrounded_word`
```

type ``cs`)``. It should change the backtick for parentheses, but it instead errors out saying: __"no such a pair found"__.

this works all right on surround.vim, therefore, it's a bug.

**Comment by braham-snyder** [comment]
https://github.com/cute-jumper/evil-embrace.el works with backquotes, in addition to allowing deleting and changing custom pairs (even "surrounding function")--useful as a reference and/or as an interim solution

**Comment by ninrod** [comment]
funny, I use evil embrace and I cannot get backticks to work.

**Comment by braham-snyder** [comment]
did you try adding (looks like it may not be documented in the README yet--I just saw it in embrace's commit log): `(add-hook 'emacs-lisp-mode-hook 'embrace-emacs-lisp-mode-hook)`?

**Comment by braham-snyder** [comment]
Ah--if you're referring to not being able to delete nor change surrounding backticks in other modes, there might be a bug in embrace.el: I can't do so in a non-emacs-lisp buffer unless I re-call `(embrace--setup-defaults)` from within the buffer. By default, looks like the global value of `embrace--pairs-list` is only the surrounding function "pair" (triggered by `f`) for me (except in modes where embrace provides specific hooks, like emacs-lisp). Are you seeing this behavior as well?

**Comment by ninrod** [comment]
I use us-international with dead keys and evil has some known issues with dead keys. I can't even get this to work in emacs-lisp-mode.

**Comment by ninrod** [comment]
does work, as demonstrated in https://github.com/emacs-evil/evil-surround/commit/cb4f0be9b42bff14fe807df6048f0fdafeff0545. Must have been a configuration issue.

**Comment by davidhaley** [comment]
> I can't do so in a non-emacs-lisp buffer unless I re-call `(embrace--setup-defaults)` from within the buffer

Just to add, in case anyone runs into this, I was trying to change surrounding backticks to equals (to format some text as inline code) within an org file (note in denote) in Doom Emacs, and this worked for me today.
