### ISSUE TITLE
Surround in insert mode

### ISSUE THREAD

**Issue by Wagk** [emacs-evil/evil-surround#105]
In vim-surround you have experimental support for surrounding your cursor in insert mode using `C-G s` and `C-S`

I'm wondering if this feature is also implemented here, and if not, is there a way I can implement it via elisp/

Cheers.

**Comment by ninrod** [comment]
hi @Wagk, certainly not because control+g is the universal binding in emacs for "get me out of here". You can certainly implement this in elisp though.

**Comment by Wagk** [comment]
Which functions should I be using?

(still very new to this elisp thing.)

**Comment by ninrod** [comment]
This seems to be an advanced undertaking. You are better off start reading some nice tutorials, like [Xah Lee's pratical elisp](http://ergoemacs.org/emacs/elisp.html).

**Comment by ninrod** [comment]
@Wagk, you are welcome to reboot this as a PR with proper tests. thanks!
