### ISSUE TITLE
custom delimeter surround: Round 2

### ISSUE THREAD

**Issue by emanresusername** [emacs-evil/evil-surround#108]
I'm fine with everything that went on in [this pr and the discussion](https://github.com/emacs-evil/evil-surround/pull/94) given the context there 
but something new came to light to me recently and i think [it](https://github.com/emacs-evil/evil-surround/pull/94)'s worth reconsidering in light of that
Even though it's not really a big deal the first time around (esp with enabling the `fd` shortcut), 
for all subsequent times you find yourself in that situation (even between restarts if buffer history is saved, like you can have with spacemacs (noidea if that's spacemacs-specific or not, just trynna provide relevant context, and that's the context i came across it in)) 
it's _*SUPER*_ convenient to have previous, often-re-used usages (e.g. `Try`, `Future`, `Option`, all of which often wrap existing type signatures/values with `[]` or `{}` in scala) in the minibuffer history so you can up/down arrow through or (regex )search through to previous usages!

**Comment by ninrod** [comment]
@emanresusername, as vim-surround does not support this, I'm not inclined to implement such a specific use case.
Nevertheless, you are welcome to try to reboot this as a pull-request with proper tests to address your usage scenario.
