### ISSUE TITLE
activate travis for evil-surround

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil-surround#110]
people, 

what can we do to activate evil-surround on travis? https://travis-ci.org/emacs-evil/evil-surround

the page says that I do not have sufficient rights for activating. 

ping @wasamasa @TheBB.

**Comment by wasamasa** [comment]
Same here.  Generally speaking, all administrative (read: GitHub-related) stuff is up to @TheBB.

**Comment by TheBB** [comment]
I activated it. :+1:
