### ISSUE TITLE
create evil surround logo

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil-surround#111]
@edkolev, would you be able to create an image for surround as you did for [evil-lion](https://cloud.githubusercontent.com/assets/1532071/23845388/6edda00c-07d0-11e7-9ea1-ffa945f03980.png)? 

Or maybe give me some pointers? I suck at image editing and your logo for evil-lion is too cool.

**Comment by edkolev** [comment]
Sure, this is what I did:
- tweak [this doc](https://docs.google.com/document/d/1D1_I5n8wbeGmhYeQbtjNXF2r_-T9ryc4kR0zVAz5uGw/edit?usp=sharing) until I get a good enough text
- export the text to image (or screenshot, I'm not sure what I did)
- copy the "evil tail" from [evil's logo](https://raw.githubusercontent.com/emacs-evil/evil/master/doc/logo.png) and paste it on my image - I did this with OS X's Preview (comes bundled with the OS) but stuff like MS's Paint should be able to do it as well

Let me know in case you get stuck in any step.

**Comment by edkolev** [comment]
<img width="541" alt="screen shot 2017-08-07 at 17 44 42" src="https://user-images.githubusercontent.com/1532071/29031827-276d67c0-7b98-11e7-9b20-396aee69b6fc.png">

No tail yet... :)

**Comment by ninrod** [comment]
awesome! yeah The tail is a must have!

**Comment by ninrod** [comment]
<img width="421" alt="surround" src="https://user-images.githubusercontent.com/8352747/33156355-1a2477d8-cfe0-11e7-93e7-47cc33821e37.png">

yeah! now with tail!

**Comment by ninrod** [comment]
<img width="421" alt="surround" src="https://user-images.githubusercontent.com/8352747/33156355-1a2477d8-cfe0-11e7-93e7-47cc33821e37.png">

yeah! now with tail!

**Comment by ninrod** [comment]
done!

**Comment by ninrod** [comment]
done!

**Comment by edkolev** [comment]
Nice :)

Might be a good idea to reduce its size a bit - it now has 192px height, maybe something a bit below 100px. Evil's own logo for comparison has 71px height https://raw.githubusercontent.com/emacs-evil/evil/master/doc/logo.png

**Comment by ninrod** [comment]
Sure! can you open another issue to address this so I don't forget? I'm on mobile

**Comment by ninrod** [comment]
<img width="187" alt="evil-surround" src="https://user-images.githubusercontent.com/8352747/33807810-91656488-ddc3-11e7-8029-985f28471a47.png">

Ok, new try!

**Comment by ninrod** [comment]
@edkolev, should be about the same size of evil's logo now. Thanks!
