### ISSUE TITLE
Overriding `s` keybinding?

### ISSUE THREAD

**Issue by rieje** [emacs-evil/evil-surround#116]
I want to override the `s` keybinding which is bound to `evil-surround-edit` in evil's operator state to rebind it to `evil-avy-goto-char`. I have the following but it still doesn't work:

    (evil-define-key 'operator global-map (kbd "s") #'evil-avy-goto-char)

According to an [evil maintainer](https://www.reddit.com/r/emacs/comments/6jhidr/evil_users_what_do_you_think_of_avy_and_vice_versa/djf2tos/), `evil-surround` does some hackery to get the bindings to work. How can I override the `s` key?

**Comment by ninrod** [comment]
try to not activate the evil-surround minor mode. and see if it works.

**Comment by rieje** [comment]
I'm not sure why there isn't a function for `M-x` to execute but I pasted `(turn-off-evil-surround-mode)` into the buffer, evaluated the sexp, and then it works.

Also, if I changed the binding from `s` to something that isn't used by evil-surround like `o` then it also works.

**Comment by ninrod** [comment]
there you go.

**Comment by rieje** [comment]
Sorry if noob question, but what makes evil-surround's `s` prioritize over my attempt to rebind it to something else? And how can I rebind `s` to something else for evil-surround?

**Comment by ninrod** [comment]
no problem. I am a huge noob in elisp. 

I think the hack comprises [this](https://github.com/emacs-evil/evil-surround/blob/master/evil-surround.el#L218-L221) snippet, combined with this [snippet](https://github.com/emacs-evil/evil-surround/blob/master/evil-surround.el#L218-L221)

I'd guess that you could change the minor mode binding to another key, say, 'r'. So evil-surround would be called with `yr`. then you could free up `s` to your liking. 

I'd go with that for my first try.

**Comment by rieje** [comment]
Thanks. I have the following now and it works:

    (evil-define-key 'operator evil-surround-mode-map "r" 'evil-surround-edit)
    (evil-define-key 'operator evil-surround-mode-map "s" nil)
    (evil-define-key 'operator global-map (kbd "s") #'avy-goto-char-timer)

If anyone knows a more concise or simpler way to achieve the same thing, I'd love to know.
