### ISSUE TITLE
Could evil-surround respect evil-want-change-word-to-end?

### ISSUE THREAD

**Issue by aaronjensen** [emacs-evil/evil-surround#117]
The original surround.vim treats `ysw)` the same as `yse)`, similar to how vim special cases `cw` to behave like `ce`. Evil has `evil-want-change-word-to-end` to emulate the `cw` special case. 

Unfortunately, [it is hard-coded to only work with `evil-change`](https://github.com/emacs-evil/evil/blob/dc936936666595afdbdbb4cc44c1f82e74c6802c/evil-commands.el#L309-L311). Would it be possible to support this case in `evil-surround` to better match `surround.vim`'s behavior?

Thanks!

**Comment by ninrod** [comment]
We'd have to inspect the code closely, but I think it would be possible. Feel free to submit patches for this.

**Comment by ninrod** [comment]
The spirit of the evil ecosystem tells us that If you are comming from vim, we want you to feel at home. 

So we want that evil-surround emulates closely `surround.vim` default behaviour. I think we should go for that. We want to cause the least surprise possible for vim expatriats. 

This has the added benefit of not adding to much complication in the code and in people's configs. 

What do you think?

**Comment by edkolev** [comment]
Seems to me this change will have to be made in evil. Evil will need a new variable holding a list of operators, the list will hold evil-change by default only. Then, plugins such as this one will be able to add themselves to the list.

Not sure if this is the best solution, maybe there's a another one. I suggest you try to make this change in evil and submit a PR in evil for comments.

**Comment by edkolev** [comment]
This is addressed in https://github.com/emacs-evil/evil-surround/commit/822a0f61c3fd7c55cda4e04c8590ae5144401c26

Issue can be closed.

**Comment by aaronjensen** [comment]
Awesome @edkolev, many thanks!
