### ISSUE TITLE
ds doesn't play nicely with evil-org-mode

### ISSUE THREAD

**Issue by LindyBalboa** [emacs-evil/evil-surround#123]
example:

start with ` "word" `
press `ds`cursor goes half height 
press `"` nothing happens
press `"` function returns nil
press `"` becomes ` "wo""rd" `

I guess this is because evil-org-delete overtakes the `d` keybinding. Not sure which library needs to address this.

**Comment by vyp** [comment]
Probably evil-org-mode, since the repo isn't under the emacs-evil organisation. I'm not sure though.

**Comment by ninrod** [comment]
if you uninstall evil-org-mode, and it works, then the problem lies with evil-org-mode.

**Comment by edkolev** [comment]
@LindyBalboa you could try changing `evil-surround-operator-alist` which is defined as:
```
(defcustom evil-surround-operator-alist
  '((evil-change . change)
    (evil-delete . delete))
```

to also include `evil-org-delete` like so:
`(add-to-list 'evil-surround-operator-alist '(evil-org-delete . delete))`

If that works, I suggest you make a PR to evil-org's repo.

**Comment by ninrod** [comment]
closing because the problem mostly is configuration related.

**Comment by zhixing2017** [comment]
It works well.

`(add-to-list 'evil-surround-operator-alist '(evil-org-delete . delete))`
