### ISSUE TITLE
type 'S' in virtual mode actually delete the selected words

### ISSUE THREAD

**Issue by TangMonk** [emacs-evil/evil-surround#126]
so cannot add surround to words

**Comment by ninrod** [comment]
cannot reproduce.

**Comment by TangMonk** [comment]
@ninrod capital `S` not work, but lower case `s` will work

**Comment by ninrod** [comment]
capital `S` does work. I just tested it. it is surely something in your end.

**Comment by iyerr3** [comment]
In case if you're seeing this after using using Spacemacs, here's the explanation: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#the-vim-surround-case
