### ISSUE TITLE
Can't dot repeat when surrounding with counted movements

### ISSUE THREAD

**Issue by jvmcarneiro** [emacs-evil/evil-surround#133]
When I surround with a count like `ys2w"` and try to repeat it with `.`, it does so as if I didn't input any count (`ysw"`).

For example:
Using `ys2w"` on  a text fragment like `-word` yields `"-word"`;
Dot repeating it on  another fragment `-another` yields `"-"another`.

Am I missing something? Is this expected behaviour?

**Comment by ninrod** [comment]
I suspect this: https://github.com/emacs-evil/evil/issues/9

**Comment by justbur** [comment]
I didn't change anything that would affect `ysiw"`. This is a different problem. My changes only affected surrounding with functions or tags. 

By the way, in general the way evil-surround implements repeat (especially for `ys`) is pretty brittle and probably should be rewritten.

**Comment by ninrod** [comment]
@justbur, maybe related to https://github.com/emacs-evil/evil/issues/9?

yeah. I wish I had the lisp and evil knowledge to do it.

**Comment by dsdshcym** [comment]
This patch makes repeat work with counted motion: 
[evil-this-motion-count.diff.txt](https://github.com/emacs-evil/evil-surround/files/4677645/evil-this-motion-count.diff.txt)

But I'm not sure if it's the right way to fix this issue.

**Comment by ninrod** [comment]
thank you @dsdshcym. 

Do you want to fill out a PR? You could include a test to verify that the behaviour is correctly implemented.

**Comment by ninrod** [comment]
346d4d8 by @dsdshcym closes this.
