### ISSUE TITLE
Unclear how to trigger custom evil-surround-pair

### ISSUE THREAD

**Issue by amilkov3** [emacs-evil/evil-surround#136]
I don't understand how these triggers work from the README

```lisp
(setq-default evil-surround-pairs-alist (cons '(?~ . ("{-" . "-}"))
                                                evil-surround-pairs-alist))
```
When highlighting say `hello` in visual mode, then pressing `s~` simply outputs `~hello~` not `{-hello-}`. I've tried with other trigger chars as well

**Comment by edkolev** [comment]
This works for me, I haven't tested your code:

```
(push '(?~ . ("{- " . " -}")) evil-surround-pairs-alist)
```

**Comment by ninrod** [comment]
try this: 

```elisp
(with-eval-after-load 'evil-surround
      (evil-add-to-alist
       'evil-surround-pairs-alist ;; use non-spaced pairs when surrounding with an opening brace evil-surround/issues/86
       ?\( '("(" . ")")
       ?\[ '("[" . "]")
       ?\{ '("{" . "}")
       ?\) '("( " . " )")
       ?\] '("[ " . " ]")
       ?\} '("{ " . " }")))
```

**Comment by amilkov3** [comment]
@edkolev's solution worked

**Comment by ninrod** [comment]
yes. thanks. done.

**Comment by amilkov3** [comment]
@edkolev the custom trigger appears to only work in `.spacemacs`. in any other file, evil-surround still works but its not picking up the trigger i.e. visual select `hello`,  press `s~` outputs `~hello~`

**Comment by edkolev** [comment]
@amilkov3 yes, it's a buffer local var https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer_002dLocal-Variables.html

```elisp
    (setq-default evil-surround-pairs-alist
              (push '(?~ . ("{- " . " -}")) evil-surround-pairs-alist)))
```

**Comment by amilkov3** [comment]
@edkolev ah k. not particularly familiar with elisp but @ninrod's changes to the README use `setq-default` so should've caught this. closing
