### ISSUE TITLE
Package won't load

### ISSUE THREAD

**Issue by boardfish** [emacs-evil/evil-surround#137]
Hi there! Pretty fresh to Emacs, but surround.vim is probably one of the most useful things there is to Vim so I'm instaling this first. I've successfully got EVIL and evil-leader working, but evil-surround is strangely not working. Here's my `.emacs` so far:

```
(require 'package)

; List the packages you want
(setq package-list '(evil
                     evil-leader
		     evil-surround))

; Add Melpa as the default Emacs Package repository
; only contains a very limited number of packages
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)

; Activate all the packages (in particular autoloads)
(package-initialize)

; Update your local package index
(unless package-archive-contents
  (package-refresh-contents))

; Install all missing packages
(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))

(require 'evil)
(evil-mode t)

(require 'evil-leader)
(global-evil-leader-mode)
(evil-leader/set-leader ",")
(evil-leader/set-key
  "b" 'switch-to-buffer
"w" 'save-buffer)

(require 'evil-surround)
```

I've tried installing `evil-surround` with `package-install`. The package didn't fail to install, but it also didn't load on reloading Emacs.

**Comment by edkolev** [comment]
`require` loads the elips code, without binding any keys to call the newly loaded code.

The most straightforward way to bind keys, as stated in the README, is to call `(global-evil-surround-mode 1)`

**Comment by ninrod** [comment]
@boardfish I think that your problem is solved with @edkolev's tip. We should be able to safely close this. Welcome aboard the evil community. I was a vim user two and loved surround.vim. (still do).
