### ISSUE TITLE
Space being added inside braces

### ISSUE THREAD

**Issue by Hi-Angel** [emacs-evil/evil-surround#138]
I just upgraded to version `evil-surround-20180102.601`, and found a new unpleasant side-effect: upon making a selection, and pressing `S(` the selected text gets surrounded with braces + spaces. Before it were just braces. Is there a way to disable that?

Steps to reproduce:

1. In \*scratch\* buffer select a word `buffer`
2. Press `S(`

Expected: the text `(buffer)`
Actual: the text `( buffer )`

**UPD**: FTR, on the other computer, where `evil-surround` with previous behavior is still installed, it's `20170124.1110` version.

**Comment by Dickby** [comment]
try `s)` or `sb`

**Comment by Hi-Angel** [comment]
Oh, yeah, the closing braces works. Furthermore, I see that there's no spaces inserted for plain characters *(like if I surround a word with \* in markdown mode)*, so I guess I can live with it.

Thanks!

**Comment by edkolev** [comment]
`(` - adds space
`)` - doesn't add space

The behaviour is the same for the other brackets. This is in line with vim-surround's behaviour.
