### ISSUE TITLE
Surround includes newline

### ISSUE THREAD

**Issue by tsoernes** [emacs-evil/evil-surround#139]
- Bug report

# Environment

Emacs version: 25.3.1
Operating System: Fedora 27
Evil version: git d4017b1c
Graphical/Terminal: X

# Reproduction steps
- Start Emacs
- Make buffer
```
abc
def
```
- Set cursor on `a`
- Go into visual mode
- <$>
- evil-surround-region X

# Expected behavior
```
XabcX
def
```

# Actual behavior
```
Xabc
Xdef
```

**Comment by ninrod** [comment]
Cannot reproduce. 

what do you type exactly on these lines?

`<$>`
`evil-surround-region X`
