### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by lazygreed** [emacs-evil/evil-surround#140]
Can you add functionality to add words after surroundings into them?
aka `M-e` in vim-surround

**Comment by ninrod** [comment]
hi, can you provide an example?

**Comment by edkolev** [comment]
Seems like you already have a working workflow, how would surround improve that?

Do you want something to insert () when you enter (? If so, you can look into electric pair more or smartparens.

**Comment by lazygreed** [comment]
it's vim screencast, I can't reproduce this in emacs, or I don't know how

**Comment by Dickby** [comment]
smartparens and paredit have functions like that. (slurp and barf)

**Comment by lazygreed** [comment]
oh ok, I found it, thank you guys
