### ISSUE TITLE
custom pair ** doesn't work.

### ISSUE THREAD

**Issue by introom** [emacs-evil/evil-surround#143]
```
  (setq-default evil-surround-pairs-alist
                (cons '(?* . ("*" . "*")) (default-value 'evil-surround-pairs-alist)))
```

for `*asdf*`, `ds*` doesn't work

**Comment by ninrod** [comment]
yeah this kind of request is becoming common, I think I'll write up an entry in the readme about this. 

for reference, see [this](https://github.com/emacs-evil/evil-surround/issues/141#issuecomment-423296243) answer.

```emacs-lisp
(defmacro define-and-bind-quoted-text-object (name key start-regex end-regex)
    (let ((inner-name (make-symbol (concat "evil-inner-" name)))
          (outer-name (make-symbol (concat "evil-a-" name))))
      `(progn
         (evil-define-text-object ,inner-name (count &optional beg end type)
           (evil-select-paren ,start-regex ,end-regex beg end type count nil))
         (evil-define-text-object ,outer-name (count &optional beg end type)
           (evil-select-paren ,start-regex ,end-regex beg end type count t))
         (define-key evil-inner-text-objects-map ,key #',inner-name)
         (define-key evil-outer-text-objects-map ,key #',outer-name))))

  (define-and-bind-quoted-text-object "pipe" "|" "|" "|") ; just for sake of example
  
  (define-and-bind-quoted-text-object "dollar" "$" "\\$" "\\$") ; another example, escaping $
(define-and-bind-quoted-text-object "slash" "*" "*" "*") ; this is the object you want
```

**Comment by introom** [comment]
yes. it works.

**Comment by ninrod** [comment]
I'm sorry, what exactly are you trying to achieve?

**Comment by introom** [comment]
I was trying to solve ds*,

from the readme description, modifying evil-surround-pairs-alist seems enough.

**Comment by ninrod** [comment]
right, but the macro [here](https://github.com/emacs-evil/evil-surround/issues/143#issuecomment-427643588) solves all this issues, yes?

**Comment by introom** [comment]
yes. it solves the issue.

**Comment by ninrod** [comment]
@introom, actually, you are trying to create a pair like this: 

```lisp
`pair'
```

Is that right?

**Comment by introom** [comment]
Originally, I'd like to create a par like
`*pair*` 
with `evil-surround-pairs-alist` . but `ds*` doesn't work.

For this: https://github.com/emacs-evil/evil-surround/issues/143#issuecomment-427661697

it was taken from the readme, but cs and ds doesn't work too.

**Comment by ninrod** [comment]
All right, readme improved.
