### ISSUE TITLE
Any plans to support Previous and Next text objects?

### ISSUE THREAD

**Issue by jjzmajic** [emacs-evil/evil-surround#152]
I mean something like [this](https://github.com/wellle/targets.vim#next-and-last-quote). Or is there already a way to do this that I'm missing?

**Comment by ninrod** [comment]
@jjzmajic, you are looking for [targets.el](https://github.com/noctuid/targets.el) or for it's sucessor: [things.el](https://github.com/noctuid/things.el)

**Comment by jjzmajic** [comment]
I'm aware of the projects, but as far as I understand it they're fairly early stage and have no dependencies on evil (so I assumed they were unrelated). I'll happily jump into hacking on them if those are what will be used to implement this feature in the future in evil (Will they be?). Just wanted to make sure I wasn't missing something.

**Comment by ninrod** [comment]
you should try targets.el. it [does have](https://github.com/noctuid/targets.el/blob/master/targets.el#L7) a dependency on evil
