### ISSUE TITLE
ruby: "no surrounding delimiters found" for simple case

### ISSUE THREAD

**Issue by Silex** [emacs-evil/evil-surround#154]
Hello,

``` ruby
SocialShareButton.configure do |config|
  config.allow_sites = %w{twitter facebook pinterest linkedin}
end
```

When I try to `cs{(` when the cursor is on "facebook" it fails.

**Comment by ninrod** [comment]
very interesting. seems to be an issue related to ruby-mode.

**Comment by ninrod** [comment]
I think the problem lies [here](https://github.com/jwiegley/ruby-mode/blob/master/ruby-mode.el#L518-L539). It is doing something with the definition of the single quote region. try to issue a `vi'` and you will see.

**Comment by Silex** [comment]
@ninrod thanks for the investigation.

Hum, does evil-surround actually defer some logic to the major modes? In my head, I pictured `cs{(` as some code inside evil-surround that found the previous `{` and next `}` and replaced that...

**Comment by ninrod** [comment]
Yes it does. You can see that it works in text-mode or other mode. I bet it works in python-mode, for instance. 

To understand  the specific mechanism that dictates this behaviour, you have to begin [here](https://github.com/emacs-evil/evil-surround/blob/master/evil-surround.el#L185-L196)

```elisp
(defun evil-surround-outer-overlay (char)
  "Return outer overlay for the delimited range represented by CHAR.
This overlay includes the delimiters.
See also `evil-surround-inner-overlay'."
  (let ((outer (lookup-key evil-outer-text-objects-map (string char))))
    (when (functionp outer)
      (setq outer (funcall outer))
      (when (evil-range-p outer)
        (evil-surround-trim-whitespace-from-range outer "[[:space:]]")
        (setq outer (make-overlay (evil-range-beginning outer)
                                  (evil-range-end outer)
                                  nil nil t))))))
```  
I understand that Evil surround depends on core evil functions to find the regions determined by the text object you are using. In turn, evil functions rely on information which can be overwritten by modes to determine the precise range of the text objects.

**Comment by Silex** [comment]
Great explanation :+1: :heart_eyes: 

This is complex indeed. I found this which seems related:

``` elisp
(defun ruby-syntax-propertize-percent-literal (limit)
  (goto-char (match-beginning 2))
  (let* ((op (char-after))
         (ops (char-to-string op))
         (cl (or (cdr (aref (syntax-table) op))
                 (cdr (assoc op '((?< . ?>))))))
         parse-sexp-lookup-properties)
    (save-excursion
      (condition-case nil
          (progn
            (if cl              ; Paired delimiters.
                ;; Delimiter pairs of the same kind can be nested
                ;; inside the literal, as long as they are balanced.
                ;; Create syntax table that ignores other characters.
                (with-syntax-table (make-char-table 'syntax-table nil)
                  (modify-syntax-entry op (concat "(" (char-to-string cl)))
                  (modify-syntax-entry cl (concat ")" ops))
                  (modify-syntax-entry ?\\ "\\")
                  (save-restriction
                    (narrow-to-region (point) limit)
                    (forward-list))) ; skip to the paired character
              ;; Single character delimiter.
              (re-search-forward (concat "[^\\]\\(?:\\\\\\\\\\)*"
                                         (regexp-quote ops)) limit nil))
            ;; Found the closing delimiter.
            (put-text-property (1- (point)) (point) 'syntax-table
                               (string-to-syntax "|")))
        ;; Unclosed literal, do nothing.
        ((scan-error search-failed))))))
```

**Comment by ninrod** [comment]
@Silex this snippet really smells like the culprit. 

To test this you would have to toy with this function a bit and see if it stops interfering with the curly braces text object. 

With my extreme limitation in elisp I'd begin with removing the `modify-syntax-entry` lines and see if it works.

**Comment by Silex** [comment]
Okay, I just tested and if you comment the `(ruby-syntax-propertize-percent-literal end)` near the end, then everything works as expected.

``` elisp
(defun ruby-syntax-propertize (start end)
  "Syntactic keywords for Ruby mode.  See `syntax-propertize-function'."
  (let (case-fold-search)
    (goto-char start)
    (remove-text-properties start end '(ruby-expansion-match-data))
    (ruby-syntax-propertize-heredoc end)
    (ruby-syntax-enclosing-percent-literal end)
    (funcall
     (syntax-propertize-rules
      ;; $' $" $` .... are variables.
      ;; ?' ?" ?` are character literals (one-char strings in 1.9+).
      ("\\([?$]\\)[#\"'`:?]"
       (1 (if (save-excursion
                (nth 3 (syntax-ppss (match-beginning 0))))
              ;; Within a string, skip.
              (ignore
               (goto-char (match-end 1)))
            (put-text-property (match-end 1) (match-end 0)
                               'syntax-table (string-to-syntax "_"))
            (string-to-syntax "'"))))
      ;; Symbols with special characters.
      ("\\(^\\|[^:]\\)\\(:\\([-+~]@?\\|[/%&|^`]\\|\\*\\*?\\|<\\(<\\|=>?\\)?\\|>[>=]?\\|===?\\|=~\\|![~=]?\\|\\[\\]=?\\)\\)"
       (3 (unless (nth 8 (syntax-ppss (match-beginning 3)))
            (goto-char (match-end 0))
            (string-to-syntax "_"))))
      ;; Part of method name when at the end of it.
      ("[!?]"
       (0 (unless (save-excursion
                    (or (nth 8 (syntax-ppss (match-beginning 0)))
                        (let (parse-sexp-lookup-properties)
                          (zerop (skip-syntax-backward "w_")))
                        (memq (preceding-char) '(?@ ?$))))
            (string-to-syntax "_"))))
      ;; Backtick method redefinition.
      ("^[ \t]*def +\\(`\\)" (1 "_"))
      ;; Ternary operator colon followed by opening paren or bracket
      ;; (semi-important for indentation).
      ("\\(:\\)\\(?:[\({]\\|\\[[^]]\\)"
       (1 (string-to-syntax ".")))
      ;; Regular expressions.  Start with matching unescaped slash.
      ("\\(?:\\=\\|[^\\]\\)\\(?:\\\\\\\\\\)*\\(/\\)"
       (1 (let ((state (save-excursion (syntax-ppss (match-beginning 1)))))
            (when (or
                   ;; Beginning of a regexp.
                   (and (null (nth 8 state))
                        (save-excursion
                          (forward-char -1)
                          (looking-back ruby-syntax-before-regexp-re
                                        (point-at-bol))))
                   ;; End of regexp.  We don't match the whole
                   ;; regexp at once because it can have
                   ;; string interpolation inside, or span
                   ;; several lines.
                   (eq ?/ (nth 3 state)))
              (string-to-syntax "\"/")))))
      ;; Expression expansions in strings.  We're handling them
      ;; here, so that the regexp rule never matches inside them.
      (ruby-expression-expansion-re
       (0 (ignore (ruby-syntax-propertize-expansion))))
      ("^=en\\(d\\)\\_>" (1 "!"))
      ("^\\(=\\)begin\\_>" (1 "!"))
      ;; Handle here documents.
      ((concat ruby-here-doc-beg-re ".*\\(\n\\)")
       (7 (when (and (not (nth 8 (save-excursion
                                   (syntax-ppss (match-beginning 0)))))
                     (ruby-verify-heredoc (match-beginning 0)))
            (put-text-property (match-beginning 7) (match-end 7)
                               'syntax-table (string-to-syntax "\""))
            (ruby-syntax-propertize-heredoc end))))
      ;; Handle percent literals: %w(), %q{}, etc.
      ((concat "\\(?:^\\|[[ \t\n<+(,=*]\\)" ruby-percent-literal-beg-re)
       (1 (unless (nth 8 (save-excursion (syntax-ppss (match-beginning 1))))
            ;; Not inside a string, a comment, or a percent literal.
            (ruby-syntax-propertize-percent-literal end)
            (string-to-syntax "|")))))
     (point) end)))
```

I have no clue what you break by commenting that part out, as the highlighting looks alright. Probably that you break some ruby motion?

**Comment by ninrod** [comment]
ok, you are onto something. Parallel to this you could try [enhanced ruby-mode](https://melpa.org/#/enh-ruby-mode). Maybe there you don't have this problem in the first place.

Can you post a link to that snippet? I'm having problems finding it.

**Comment by Silex** [comment]
The link is https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/ruby-mode.el#L1856

It does not happen with enhanced ruby mode, provided that I never activate ruby-mode before.

**Comment by ninrod** [comment]
@Silex, I believe the problem lies in [this](https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/ruby-mode.el#L1975-L1988) snippet, which defines the `ruby-syntax-propertize-percent-literal` function:

```elisp
(defun ruby-syntax-propertize-percent-literal (limit)
  (goto-char (match-beginning 2))
  (let* ((op (char-after))
         (ops (char-to-string op))
         (cl (or (cdr (aref (syntax-table) op))
                 (cdr (assoc op '((?< . ?>))))))
         parse-sexp-lookup-properties)
    (save-excursion
      (condition-case nil
          (progn
            (if cl              ; Paired delimiters.
                ;; Delimiter pairs of the same kind can be nested
                ;; inside the literal, as long as they are balanced.
                ;; Create syntax table that ignores other characters.
                (with-syntax-table (make-char-table 'syntax-table nil)
                  (modify-syntax-entry op (concat "(" (char-to-string cl)))
                  (modify-syntax-entry cl (concat ")" ops))
                  (modify-syntax-entry ?\\ "\\")
                  (save-restriction
                    (narrow-to-region (point) limit)
                    (forward-list))) ; skip to the paired character
              ;; Single character delimiter.
              (re-search-forward (concat "[^\\]\\(?:\\\\\\\\\\)*"
                                         (regexp-quote ops)) limit nil))
            ;; Found the closing delimiter.
            (put-text-property (1- (point)) (point) 'syntax-table
                               (string-to-syntax "|")))
        ;; Unclosed literal, do nothing.
        ((scan-error search-failed))))))
```

there are many, many modifications in the syntax table here.

**Comment by Silex** [comment]
@ninrod: sure, the thing is we don't even know what the "problem" is or what feature this snippet addresses.

So far all I know is that if I don't call `ruby-syntax-propertize-percent-literal` the bug is gone, and probably that this code was there for a reason but I don't know what.

**Comment by ninrod** [comment]
what if you toy with the function definition itself?

**Comment by Silex** [comment]
> what if you toy with the function definition itself?

Why? What am I trying to do?

I know this function is supposed to propertize the percent literal for ruby's syntax, but I don't know *why*.

Is it to allow other `ruby-foo` function to properly behave when it encounters percent-literal? Is it to do special code highlighting? Is it to check for errors?

We first need to understand what this function is supposed to do and why and then we can start looking for bugs.

Maybe we should simply ask on the mailing list at this point :wink:

**Comment by ninrod** [comment]
I think that what we are trying to do is to discover the exact line that causes the incompatibility with evil. 
Then we can figure out why those lines are important and if there is another way to achieve the same effect but in an evil compatible way/

I think that as a last try you could try to comment out the modify-syntax-table commands inside this function. Just a hunch.

**Comment by Silex** [comment]
Okay, here's Stefan's *amazing* answer:

-------------

> We are trying to solve a bug in evil-surround at
> https://github.com/emacs-evil/evil-surround/issues/154. The bug is that
> percent literals refuse to be replaced when you try to replace a pair of
> "{}" with "()" using evil-surround, because ruby.el modifies the percent
> literal syntax table in a special way (when we use `fundamental-mode' then
> things works as expected).

ruby-mode uses syntax-propertize to make it so that

    config.allow_sites = %w{twitter facebook pinterest linkedin}

is treated somewhat like

    config.allow_sites = "w{twitter facebook pinterest linkedin"

So if you go to the end of the line and try to skip back over the
previous `sexp` you'll end up in front of the `%` rather than in front
of the `{`.

The purpose is probably to handle things like:

    config.allow_sites = %w{twitter facebook # pinterest linkedin}

where the `#` would otherwise be taken as the beginning of a comment.

> If I comment out the call to `ruby-syntax-propertize-percent-literal', then
> the bug in evil-surround is gone, and everything just looks the same
> visually (the percent literals are correctly highlighted).

Not sure what "comment out the call" means exactly, but from my reading
of the code, it would result in mayhem (the %w{ above would probably
be highlighted as if he extended to the end of the buffer).

In order to interact better with things like Evil's
delimiter-replacement, ruby-mode.el could be changed so that instead of
marking the opening `%` and the closing `}` with the `|` syntax, it
would mark the `%` and `w` part with `'` syntax and then arrange to mark
the inside of the delimited text with an ad-hoc syntax table that
doesn't treat `#` as a comment started nor `"` as a string delimiter
(i.e., the same syntax-table used by the `with-syntax-table`
in `ruby-syntax-propertize-percent-literal`).  Or alternatively, it
could look for things like `#` and `"` and give them a `.` syntax.

**Comment by ninrod** [comment]
Great work. Well, seems like, a change in ruby-mode is to be employed in order to fix this

**Comment by Silex** [comment]
> Great work. Well, seems like, a change in ruby-mode is to be employed in order to fix this

Yes, that or some trickery in evil-surround to handle ruby-mode specially. Maybe it could use `fundamental-mode` rules for ruby-mode, but that probably is tricky to achieve.

**Comment by ninrod** [comment]
Yes, exactly, I think that the main idea behind this implementation is to use the already parsed file through the syntax-table. When the user opens the file using a mode, the file is already parsed so that all the delimiters are already calculated and evil simply reuses that instead of calculating the delimiters again.

**Comment by Silex** [comment]
> I will keep this issue open, but I really think that this issue belongs in core evil because, for instance, `ci{` does not work with your provided sample using ruby-mode and just "pure evil".

Good catch! I'll likely transfer this issue to evil then.

**Comment by Silex** [comment]
Continuing in the evil issue.
