### ISSUE TITLE
Repeating a tag change that preserves attributes doesn't work

### ISSUE THREAD

**Issue by jamesnvc** [emacs-evil/evil-surround#161]
e.g. with the cursor as indicated on the "f" of "foo"

```
<div attr="1">[f]oo</div><div attr="2">bar</div>
```

entering `cst<span` results in

```
<span attr="1">foo</span><div attr="2">bar</div>
```

as expected. However, moving the cursor to the "b" of bar and hitting `.` results in  

```
<span attr="1">foo</span>< attr="2">bar</>
```

**Comment by jamesnvc** [comment]
Possibly related to #159 ?

**Comment by jamesnvc** [comment]
Ah, this is just because evil-surround-change isn't wrapped in `evil-surround-call-with-repeat`, I think.

**Comment by ninrod** [comment]
I cannot reproduce the behaviour. my attrs are awalys erased when changing the surround tag.

**Comment by ninrod** [comment]
solved. see #162
