### ISSUE TITLE
Keep visual state after surrounding

### ISSUE THREAD

**Issue by mpanarin** [emacs-evil/evil-surround#163]
Is there a way to keep the visual state after the surrounding? sometimes I need to wrap my text in `}}` and reselecting it is a bit annoying.

**Comment by ninrod** [comment]
I belive there is a way to do that without visually selecting. Can you provide a specific use case?

**Comment by edkolev** [comment]
Use gv to reselect

Or use a text object instead of visual selection in the first place. Then
repeat it with dot .

**Comment by mpanarin** [comment]
fixed my issue with gv, thanks
