### ISSUE TITLE
Surround friendly text objects must be declared on global map

### ISSUE THREAD

**Issue by itai33** [emacs-evil/evil-surround#164]
`evil-surround-(inner|outer)-overlay` matches the inputted character against [the global text object map](https://github.com/emacs-evil/evil-surround/blob/master/evil-surround.el#L187). This means that in order to have minor-mode specific text objects that interact with `evil-surround`, they must be defined on the global keymap, where they might conflict with other mappings.

Would it be possible to add support for reading text objects from a local keymap? This seems very doable, and I'd be happy to make a PR.

**Comment by ninrod** [comment]
@itai33, since we have a decent test set now, feel free to do it. 

Ideally, the PR should add some tests to verify this funcionality.

**Comment by itai33** [comment]
excellent! just to be sure, when you say tests, you mean things using `ert` in `evil-surround-test.el` right?

**Comment by itai33** [comment]
@ninrod [in this line](https://github.com/emacs-evil/evil-surround/blob/master/test/evil-surround-test.el#L44), you include as part of your test `csw)`, however this leads to the error `No such a pair found` (which also causes the test to fail). In neovim using vim-surround, this does surround the word with parentheses as expected. Is the test wrong or is this a bug?

**Comment by ninrod** [comment]
Yes. You shoud try using `make test`, as described in the readme, or make emacs. It  uses a naked emacs with only the absolute minimum dependencies you need.

**Comment by itai33** [comment]
That works, thank you. I'll submit a PR as soon as I finish writing the added tests.

**Comment by ninrod** [comment]
#165 by @itai33 successfully implements the behaviour.
