### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by qazxwecvr** [emacs-evil/evil-surround#169]
I am using doom emacs.
After trying `ys` or `cs` (and probably others as well) emacs displays:
```
Wrong number of arguments: (2 . 4), 0
```
Then, whenever I try to perform any commands (with `:`) it gives me the same error message and does not allow me to type a command. The only thing I can do if I wish to return to normal is exit emacs, saving files, and reopening emacs.
Anything you can do to help is appreciated.

**Comment by ninrod** [comment]
@qazxwecvr , please try to reproduce your specific problem with `make emacs` and see if the problem still happens. You can learn more about this possibility in the readme.

**Comment by qazxwecvr** [comment]
Everything worked fine when I used `make && make emacs`. When I run emacs normally and use `y C-h k s` it does what was described above, so I can't really tell what is causing the error. Is there anything else you suggest to figure out what's happening when I press these combinations?

**Comment by ninrod** [comment]
Yes, this is really common. It is a problem with your configuration.

The way I usually go about solving this is starting from the cleanest config file I can possibly come up with. 

Strip all of your configs and just start with evil and evil-surround. Make sure it works.

Now slowly add your configuration back, step by step, package after package, and test the use case after each step, until you are able to pinpoint the offending package/configuration.

Requires patience and effort, but works everytime.
