### ISSUE TITLE
broken in emacs snapshot

### ISSUE THREAD

**Issue by redguardtoo** [emacs-evil/evil-surround#171]
define-obsolete-function-alias parameters is changed in emacs 28 .

See https://github.com/manateelazycat/emacs-application-framework/pull/509/commits/1288aefeb4f3c6870a4642ac40227a38bf6e87c2

**Comment by ninrod** [comment]
@redguardtoo , thank you. Shouldn't we keep this issue open?

**Comment by redguardtoo** [comment]
I find it’s resolved in latest evil. You can delete this issue.
