### ISSUE TITLE
Actual string pairs support?

### ISSUE THREAD

**Issue by Inc0n** [emacs-evil/evil-surround#180]
I saw on a stackoverflow page that `wrap-regiona-dd-wrapper` allows you to do this:
```
(wrap-region-add-wrapper "#+BEGIN_SRC emacs-lisp\n" "#+END_SRC" "#" 'org-mode)
```
However, the following does not work on my end.
```
(push (cons ?\#'("#+begin_src \n" . "#+end_src"))
        evil-surround-pairs-alist)
```

The actual traceback and error log:
```
Debugger entered--Lisp error: (wrong-type-argument characterp 134217779)
  format("%c" 134217779)
  evil-surround-pair(134217779)
  evil-surround-region(3291 3318 line 134217779)
  funcall-interactively(evil-surround-region 3291 3318 line 134217779)
  command-execute(evil-surround-region)
```

**Comment by Inc0n** [comment]
However, for this particular application, I just discovered `C-c C-, (org-insert-structure-template)`, which I should use instead.

**Comment by ninrod** [comment]
@Inc0n , should we cloud this then?

**Comment by Inc0n** [comment]
Would it not be helpful still to look into how to add support for actual string surround? Or help me identify the error in my code that made evil-surround not working with multi-character string?
If the above cannot be fullfilled, with `C-c C-,` in place for my specific issue, then I would happily close this.
