### ISSUE TITLE
Surrounding a line inserts the second symbol on the next line

### ISSUE THREAD

**Issue by EducatedAlmost** [emacs-evil/evil-surround#181]
Calling `yssa` inserts the second `a` at the beginning of the next line instead of at the end of the current line.

Expected:
```
lmno
apqrsa
tuvw
```

Actual:
```
lmno
apqrs
atuvw
```

This happens with numerous, but not all, delimiters: `a` and all other letters, `,`, `£`, `/` are some examples I've found.

Similar behaviour was reported in #173 but this is happening in buffers WITHOUT `visual-line-mode` enabled.

**Comment by tomdl89** [comment]
Thanks for the bug report @EducatedAlmost . I can't replicate this, so maybe you can try replicating in a `make emacs` session, to eliminate interference of other elisp/packages?

**Comment by EducatedAlmost** [comment]
Indeed, @tomdl89, evil-surround works will when called with `make emacs`. Would you have any suggestions on how to debug this? Otherwise I am happy to close the issue.

**Comment by tomdl89** [comment]
@EducatedAlmost  As with most issues that look to be caused by elsip/packages, I'd suggest you bisect your config recursively. If you find the culprit, please post it here, to help the next person who has this issue.
