### ISSUE TITLE
Renaming tags not working for me

### ISSUE THREAD

**Issue by elmehalawi** [emacs-evil/evil-surround#185]
Sorry for the obtuse question, but I can't seem to get tag renaming working. For example, if I have this bit of JSX:

```jsx
<Text style={[styles.sectionTitleText, textStyle]}>{text}</Text>
```

and I have the cursor inside the tag, then do `cst<`... it ignores antying after the `<` and what I end up with is:

```jsx
<{text}<
```

I'm using doom emacs with evil-surround. Any ideas what could be causing this?

**Comment by tomdl89** [comment]
Hi @elmehalawi I don't think this is an obtuse question. I guess there may be another mode interfering with evil-surround, I'd suggest you bisect your way to the answer by commenting out / disabling half of your config (minus evil-surround, of course) and testing until you find the culprit. If you still can't find a cause, it sounds like either a doom problem (in which case make an issue there) or an issue with your emacs or env. Probably worth running a `make emacs` session (where only evil and evil surround are loaded) to test the latter. There's always a chance it's an evil-surround bug, but I'd need repro steps to investigate. Let us know how you get on

**Comment by elmehalawi** [comment]
Thanks @tomdl89 I will try that and update, I appreciate your help

**Comment by elmehalawi** [comment]
As suggested by someone in the doom-emacs repo, doing `csttdiv>` instead works. I'm not sure why, but that does work so no complaints here.
