### ISSUE TITLE
evil-surround-region no longer works with inner motion

### ISSUE THREAD

**Issue by kentonspr** [emacs-evil/evil-surround#195]
After the fix for evil-surround-region in [issue #194](https://github.com/emacs-evil/evil-surround/issues/194
) using `ysiw` inserts two `w`'s instead of surrounding the word. This occurs with any inner motion, not just `w` or `W`.

**Comment by Stebalien** [comment]
This seems to have been fixed on the latest evil master.

**Comment by kentonspr** [comment]
Confirmed working on evil commit [9f25e19](https://github.com/emacs-evil/evil/commit/9f25e190c360dc65dbcdfaef3d6408eedd5921d9)
