### ISSUE TITLE
Add a control variable to disable the padding space when using `S` to insert pairs

### ISSUE THREAD

**Issue by tlkahn** [emacs-evil/evil-surround#197]
To make my point clearer, I add a comment in the code [here](https://github.com/emacs-evil/evil-surround/commit/205c650d7fbfdbe2b917e1d90e701633a55e89df#r106953057)

**Comment by tomdl89** [comment]
I think I answered this adequately at the above link, but @tlkahn feel free to re-open this issue if you like.
