### ISSUE TITLE
Deleting surrounding tags leaves a blank line

### ISSUE THREAD

**Issue by angrybacon** [emacs-evil/evil-surround#203]
Deleting surrounding pair with `dst` from

```tsx
<Parent>
█ <Something />
</Parent>
```

To

```tsx
  
█ <Something />
  
```

(█ is the point)

Leaves blank lines around the children. Is that by design or customizable?

**Comment by tomdl89** [comment]
@angrybacon this is by design. It works the same in https://github.com/tpope/vim-surround. It's not customizable, and I think making it customizable would be non-trivial. Would your preferred logic be to delete the entire line if a deleted tag is the only thing on the line?

**Comment by angrybacon** [comment]
Thanks for confirming. I now see how that could be problematic but with automatically prettified code, I never have things like:

```tsx 
<Parent><Something>
█ <Something />
</Something></Parent>
```

>  Would your preferred logic be to delete the entire line if a deleted tag is the only thing on the line?

Yep

**Comment by tomdl89** [comment]
OK, makes sense. I'd welcome a well-considered PR to add this as an (off-by-default) option, if it doesn't make the code around deletion too complicated.
