### ISSUE TITLE
vim-sandwich style bindings

### ISSUE THREAD

**Issue by aleksandersumowski** [emacs-evil/evil-surround#209]
Is there a way to redefine the bindings to be vim-sandwich style, ie:
overtake `s` key as key sequence trigger and use:
- `sa` to add a surrounding
- `sr` to replace a surrounding
- `sd` to delete a surrounding

more detailed examples:
https://github.com/machakann/vim-sandwich

**Comment by tomdl89** [comment]
Hi @aleksandersumowski it's not trivial to do in a generic way, but I think I've got the functionality you want working with the following elisp:

```elisp
(evil-define-command evil-sandwich (char)
  (interactive (evil-surround-input-char))
  (call-interactively
   (pcase char
     (?a #'evil-surround-region)
     (?r #'evil-surround-change)
     (?d #'evil-surround-delete))))

(evil-define-key 'normal evil-surround-mode-map "s" 'evil-sandwich)
```

Lemme know if that works for you.

**Comment by tomdl89** [comment]
Assuming this fixes. Feel free to reopen if not.

**Comment by aleksandersumowski** [comment]
I'm still strugling to make this keybinding work in Doom Emacs. The binding remains bound to `evil-snipe`. But I guess thats outside the scope of evil surround 🤷

**Comment by tomdl89** [comment]
I don't use Doom or evil-snipe, but having looked at the readme, I think this would fix that problem:
```elisp
(evil-define-key '(normal motion) evil-snipe-local-mode-map "s" nil)
```
and then define whatever key you want to use instead in `evil-snipe-local-mode-map` and you'll be fine.

**Comment by aleksandersumowski** [comment]
that has worked, but now 
`s runs the command evil-substitute (found in evil-normal-state-map), which is an
interactive native-compiled Lisp function in ‘evil-commands.el’.`

There should be a way to simply override a mapping ...

**Comment by aleksandersumowski** [comment]
wait, wouldn't this only work if I'm already in `evil-surround-mode`?
`(evil-define-key 'normal evil-surround-mode-map "s" 'evil-sandwich)`

**Comment by tomdl89** [comment]
Sorry to be unclear. What I was suggesting was to put something like this in your config:
```elisp
(evil-define-command evil-sandwich...)

(evil-define-key '(normal motion) evil-snipe-local-mode-map "s" nil)
(evil-define-key 'normal evil-surround-mode-map "s" 'evil-sandwich)
```
Because it's quite clear. You can indeed avoid binding "s" to `nil` in `evil-snipe-local-mode-map`, by quoting `evil-surround-map` like so:

```elisp
(evil-define-command evil-sandwich...)

(evil-define-key 'normal 'evil-surround-mode-map "s" 'evil-sandwich)
```

But that very subtle difference (just the `'`) is too easy to miss imo, so I prefer unbinding beforehand, as above. That's up to you.

WRT
> wait, wouldn't this only work if I'm already in evil-surround-mode?

The keybinding will only work if evil-surround-mode is enabled. But defining the key can be done before/after it is enabled. Modes being on or off is a bit of a confusing concept, as the functions are all available either way, as long as they are loaded. If you want to use evil-sandwich without evil-surround being enabled, bind it in another keymap.

**Comment by AssaultAlpaca** [comment]
I have a related question. How can I set the bindings to instead be:

- `s` to add a surrounding
- `sr` to replace a surrounding
- `sd` to delete a surrounding

`r` and `d` are unbound in `evil-operator-state-map`, so there
shouldn't be any conflicts with evils default keybindings.

This is how I have my keybinds in vim and I prefer to keep it that
way.

**Comment by tomdl89** [comment]
@AssaultAlpaca yeah it's possible. You'd probably want to put `r` and `d` in the `evil-operator-state-map` bound to functions that check the operator like so:
```elisp
(defun sr ()
  (interactive)
  (and (eq 'evil-surround-region evil-this-operator)
       (call-interactively 'evil-surround-change))
  (setq evil-inhibit-operator t))

(evil-define-key 'operator evil-surround-mode-map "r" 'sr)
```
[updated to reflect most recent advice]

**Comment by AssaultAlpaca** [comment]
Hi, thanks for the quick reply. I have some issues with your suggestion. Here is what I have changed my evil-surround config to for testing:

```emacs-lisp
(defun evil-sandwich-delete ()
  (interactive)
  (and (eq 'evil-surround-region evil-this-operator)
       (call-interactively 'evil-surround-delete))
  (evil-normal-state))

(define-key evil-operator-state-map "d" 'evil-sandwich-delete)
(define-key evil-normal-state-map "s" 'evil-surround-region)
```

I can add surrounds just fine with `ss"` and I can then delete the quotes with `sd"`. But the next keypress adds another surround. Here is an example:

```
;; _ is point
he_llo
;; ss"
_"hello"
;; lllsd"
hel_lo
;; k
_khekllo
```

**Comment by AssaultAlpaca** [comment]
@tomdl89

**Comment by AssaultAlpaca** [comment]
Upon further reflection I believe an issue is the line `(evil-normal-state)` doesn't properly reset state as is intended.

**Comment by tomdl89** [comment]
Yeah, maybe worth trying `evil-force-normal-state` instead. I'm afk right now but can take a look later if that doesn't work.

**Comment by AssaultAlpaca** [comment]
Your advice sadly doesn't work. Same issue.

**Comment by AssaultAlpaca** [comment]
`keyboard-quit` in its place seems to work. But It feels a bit iffy to use quit this way.

**Comment by tomdl89** [comment]
`(setq evil-inhibit-operator t)` is probably what you want. Updated above.

**Comment by AssaultAlpaca** [comment]
Almost there, but now instead of making a surround, it just ignores the next motion.

**Comment by tomdl89** [comment]
Ah sorry, I forgot you were doing
```elisp
(define-key evil-normal-state-map "s" 'evil-surround-region)
```
so `evil-surround-region`'s `interactive` form is still waiting for input after `evil-sandwich-delete` has done it's thing. Off the top of my head, I can't think of a better way to early exit than to  keyboard-quit it.

**Comment by AssaultAlpaca** [comment]
Ok, then I guess I will have to be fine with `keyboard-quit` for now. Thank you for your help. I am posting the relevant part of my config below in case someone wants to do the same in the future:

```emacs-lisp
;; TODO `keyboard-quit' should probably be switched for something else
(defun evil-sandwich-change ()
  (interactive)
  (and (eq 'evil-surround-region evil-this-operator)
       (call-interactively 'evil-surround-change))
  (keyboard-quit))

(defun evil-sandwich-delete ()
  (interactive)
  (and (eq 'evil-surround-region evil-this-operator)
       (call-interactively 'evil-surround-delete))
  (keyboard-quit))

;; Keybinds like vim-sandwich: sc, and sd
(define-key evil-operator-state-map "r" 'evil-sandwich-change)
(define-key evil-operator-state-map "d" 'evil-sandwich-delete)
(define-key evil-normal-state-map "s" 'evil-surround-region)
(define-key evil-normal-state-map "S" 'evil-Surround-region)
```
