### ISSUE TITLE
Add keybinds like almost vim-sandwich

### ISSUE THREAD

**Issue by AssaultAlpaca** [emacs-evil/evil-surround#215]
Hello, I am trying to setup my my keybinds as follows:

- `s` to add a surrounding
- `sr` to replace a surrounding
- `sd` to delete a surrounding

This is almost the same as a related issue but since that one is
closed I am opening a new one.

https://github.com/emacs-evil/evil-surround/issues/209#issuecomment-2478648613

Instead of having `sa` add a surrounding I want to have it one level
flatter.

I am thinking this should be possible as `r` and `d` are unbound in
evil-operator-state-map, so there shouldn't be any conflicts with
evils default keybindings.

This is how I have my keybinds in vim and I prefer to keep it that
way.

Is this possible?

**Comment by tomdl89** [comment]
Answered where originally asked. lmk if that's unclear at all.
