### ISSUE TITLE
support latex operators

### ISSUE THREAD

**Issue by gdkrmr** [emacs-evil/evil-surround#95]
I have the following feature request:
support tex/latex operators:
$ ... $
$$ ... $$
\\[ ... \\]
\\( ... \\)
\begin{some environment} ... \end{some environment}
\command[with potential extra options]{ ... }
\left* ... \right**
where * can be any of [ ( \{ \| | . and ** any of . | \| \} ) ] also \left( can be closed with \right] for example.

**Comment by ninrod** [comment]
Hi. Can't you implement this behaviour with the custom pairs? 

https://github.com/timcharper/evil-surround#add-new-surround-pairs

**Comment by ninrod** [comment]
@gdkrmr, check [evil-embrace](https://github.com/cute-jumper/evil-embrace.el) and embrace.el. 

I strongly believe that you can implement the latex pairs with this. Feel free to reopen the issue if that's not the case.
