### ISSUE TITLE
Feature request: Allow surround to be enabled without setting up keybindings

### ISSUE THREAD

**Issue by DanPallas** [emacs-evil/evil-surround#96]
I use 's' for evil ace jump in normal and motion mode. I can't enable evil-surround without having that keybinding overridden by vim-surround. I can somewhat hackishly override the default keybinding:

`(evil-define-key 'operator evil-surround-mode-map "s" 'evil-ace-jump-char-mode)`

 It would be nice if, like tpope's vim plugin, surround could be enabled without the keybindings being made.

**Comment by ninrod** [comment]
@DanPallas, would you be able to write a fix for this?

**Comment by wbolster** [comment]
what exactly is the issue here?

i am not sure why you would need to "enable" surround mode to use this package. by loading the package, the functionality becomes available. with autoloads, this takes exactly zero lines of configuration.

the `evil-surround-mode` minor mode does only _one_ thing, namely binding keys. these are the bindings made:

```elisp
(evil-define-key 'operator evil-surround-mode-map "s" 'evil-surround-edit)
(evil-define-key 'operator evil-surround-mode-map "S" 'evil-Surround-edit)

(evil-define-key 'visual evil-surround-mode-map "S" 'evil-surround-region)
(evil-define-key 'visual evil-surround-mode-map "gS" 'evil-Surround-region)
```

so if you want to use `evil-surround` without the default bindings, just don't enable the mode. to make `S` work in visual mode, use

```elisp
(evil-define-key 'visual global-map "S" 'evil-surround-region)
(evil-define-key 'visual global-map "gS" 'evil-Surround-region)
```

note that this uses `global-map` and not `evil-surround-mode-map` (which is only active when the minor mode is enabled.

**Comment by ninrod** [comment]
Thanks @wbolster. @DanPallas, with that, can we close this?

**Comment by braham-snyder** [comment]
@wbolster I'm relatively new to emacs, but: while that would work, is that not a nonstandard workaround better-solved by separating the keybindings into their own function? Not using the provided minor mode would prevent easily toggling the bindings in the standard way, would prevent any other code from using the minor mode variable to determine whether `evil-surround` is active (and the user, for that matter--I shouldn't see`evil-surround-mode` is `nil` when `evil-surround` commands are currently bound), and could cause the user to miss updated functionality should it happen to be added within the minor mode alone.

While all of the above is relatively inconsequential--we can always just rebind the provided commands in some way or another--it adds up across every package binding keys by default.<sup>[1](#myfootnote1)</sup>

 Unfortunately, at this point, most of the many people using this package would probably be pretty annoyed if they suddenly lost their `evil-surround` key bindings for no apparent reason. Would an additional `evil-surround-inhibit-default-keybindings` option be more trouble than it's worth?

<a name="myfootnote1"><sup>1</sup></a> lawd:
```
    (defun brds/undo-evil-sp-binds ()
      ;; retain my keybindings (`evil-snipe')
      (evil-define-key 'normal evil-smartparens-mode-map
        (kbd "s") nil
        (kbd "S") nil
        (kbd "X") nil
        (kbd "x") nil)
      (evil-define-key 'visual evil-smartparens-mode-map
        (kbd "X") nil
        (kbd "x") nil))

    ;; TODO: report bug to evil-smartparens? binding keys in minor mode
    ;; activation function is terrible, no?
    (add-hook 'smartparens-enabled-hook #'evil-smartparens-mode)
    (add-hook 'evil-smartparens-mode-hook #'brds/undo-evil-sp-binds t)
```

**Comment by DanPallas** [comment]
@ninrod braham-snyder brings up a good point. I can work on a PR for this issue, but it will take me awhile as I'm very new to emacs lisp and emacs in general. I'll have to find out what the best practices are for this type of situation.

**Comment by wbolster** [comment]
this is not a problem that needs fixing. everything works as it should.

it's standard practice for packages to have commands that can be bound to keys of the user's preference (or not at all, there's always `M-x`).

the minor mode is ONLY for default keybindings. the reasoning about adding new behaviour to the minor mode or missing out on new features seems a bit uninformed to me, since the main thing this package (and many others) does is to provide some commands. the minor mode is just convenience on top.

please, do NOT change that, especially but if you do not know how packages are supposed to behave in emacs.

**Comment by ninrod** [comment]
Gentleman, see if I'm understanding correctly: @wbolster says that if you do not want the default keybindings, you just have to load the package, but not the minor mode. You then can bind the commands to whatever binds you want to. Is that right? 

If that's right, that's a very compelling argument for we to do nothing and I tend to agree with @wbolster. Perhaps we could document this in the readme, in a "use your own keybindgs" section, as it is not so obvious to people new to emacs and elisp in general. 

#99 would have to be fixed for this to be fully configurable though.

**Comment by wbolster** [comment]
as a follow-up: the original report mentions "enabling this package".

there is no such thing. there is only a) loading the package and b) using the default bindings.

if you want both a and b, use the minor mode. this is what most people want.

if you only want a, simply do not use the minor mode. instead, bind the commands yourself using evil's key binding facilities, or invoke the commands via M-x (but that's cumbersome and limited)

**Comment by braham-snyder** [comment]
> the reasoning about adding new behaviour to the minor mode or missing out on new features seems a bit uninformed to me, since the main thing this package (and many others) does is to provide some commands. the minor mode is just convenience on top.

@wbolster I wouldn't expect this to be a problem for this particular package, but does this not add up across each of the "many others"? I don't want to have to keep track of each of the packages I'm using whose minor modes I've had to circumvent.

And what about this bit:

> Not using the provided minor mode would prevent easily toggling the bindings in the standard way, would prevent any other code from using the minor mode variable to determine whether evil-surround is active (and the user, for that matter--I shouldn't see `evil-surround-mode` is `nil` when `evil-surround` commands are currently bound)

Isn't the cost of adding an `evil-surround-inhibit-default-keybindings` option that itself defaults to `nil` (so it won't affect anyone happy with the default keybindings) trivial in comparison to the above? If I pull-requested such a variable, would you be opposed?

**Comment by wbolster** [comment]
tbh, yes, i would be opposed. it would add useless complexity for no gain. over-engineering is a maintenance burden. simplicity, otoh, is awesome.

toggling fundamental add-on behaviour (like this package provides) is generally not useful. the same goes for packages adding evil text objects.

toggling behaviour is often implemented using minor modes indeed, but not every minor mode is intended as a toggle even tough it can sometimes be used as such.

many emacs packages simply provide a bunch of commands, and leave it to the user how to use these commands. minor modes provided by such packages are often just a way to turn on default behaviour, which often means default key bindings. evil-surround is like this. the main api are the functions, the minor mode is just the sauce on top.

**Comment by ninrod** [comment]
@braham-snyder, allow me to share my thoughts about some of your points brought up earlier.

>Not using the provided minor mode would prevent easily toggling the bindings in the standard way, 

I think that if you would like to switch back and forth between your bindings and the standard `evil-surround` bindings, you can come up with a function that unbinds all your evil-surround specific binds and then calls the minor mode. Maybe wrap all of that with a toggle-like function. Not easypeazy, but certainly doable.

> would prevent any other code from using the minor mode variable to determine whether evil surround is active (and the user, for that matter--I shouldn't see evil-surround-mode is nil when evil-surround commands are currently bound)

Aren't forms like `(with-eval-after-load "evil-surround" BLOCK)` tailored for scenarios like that? I think that even `(require 'evil-surround)` would work in your specific case, right?

>  I don't want to have to keep track of each of the packages I'm using whose minor modes I've had to circumvent.

@braham-snyder, I also wished that that was the case, but each emacs package is indeed a world of it's own and deserves it's own section to account for it's intricacies. Take purcell's [config](https://github.com/purcell/emacs.d/tree/master/lisp) for an example. He keeps a whole `.el` file just to configure each package he uses. So I think that in the context of configuring emacs packages, you have no choice but to babysit each package if you wan't to customize the package's behaviour, and that would include knowing when to use and when not to use the minor-mode's.

**Comment by wbolster** [comment]
> I shouldn't see evil-surround-mode is nil when evil-surround commands are currently bound

that is not at all how packages should behave. if you care about whether a command has been bound, use `(where-is)`, but keep in mind that with `evil-mode` this can become complex since evil adds states ("vim modes") to emacs, and it enables/disables keymaps for its magic.

that said, there really is no such thing as "evil-surround is active" that user would care about.

also, i cannot imagine a use case where "toggling evil-surround" makes sense. evil-surround is not a switch, it is a bunch of useful extra commands to improve the evil editing experience.

**Comment by jschaf** [comment]
For whatever it's worth, here's how I load evil-surround without using the global minor mode.  My goal was different. I'm happy with the default keybindings, but I want to delay loading the package until I invoke the keybinding.

```emacs-lisp
(use-package evil-surround
  :commands
  (evil-surround-edit
   evil-Surround-edit
   evil-surround-region
   evil-Surround-region)
  :init
  (evil-define-key 'operator global-map "s" 'evil-surround-edit)
  (evil-define-key 'operator global-map "S" 'evil-Surround-edit)
  (evil-define-key 'visual global-map "S" 'evil-surround-region)
  (evil-define-key 'visual global-map "gS" 'evil-Surround-region))
```

**Comment by edkolev** [comment]
@jschaf thank you, evil-surround was the only evil plugin that I hadn't figured how to lazy load!

**Comment by jschaf** [comment]
Glad it helped.  You might also want to check out [general.el](https://github.com/noctuid/general.el) which let me simplify that snippet to this:

```emacs-lisp
(use-package evil-surround
  :general
  (:states 'operator
   "s" 'evil-surround-edit
   "S" 'evil-Surround-edit)
  (:states 'visual
   "S" 'evil-surround-region
   "gS" 'evil-Surround-region))
```

**Comment by ninrod** [comment]
Gentleman, we have an excellent workaround to this issue in @jschaf's [comments](https://github.com/emacs-evil/evil-surround/issues/96#issuecomment-330165755) and I fully agree with @wbolster's reasoning so I'm closing this.
