### ISSUE TITLE
`.` repetition of one-key surround bindings surrounds with `i` or `a`

### ISSUE THREAD

**Issue by braham-snyder** [emacs-evil/evil-surround#99]
When `evil-surround-edit` is rebound to a single key (is that the right way to go about binding a single-key for `evil-surround`?), `.` repetition of a surround command surrounds with either `i` chars or  `a` chars instead of the desired character, depending on whether an inner/outer textobj was used.

For example, with r set to `evil-surround-edit`: `riw(.` on `word` gives `i(word)i` instead of `((word))`.

One quick workaround for those looking for one is to edit the definition of `evil-surround-edit`: just replace the `evil-surround-call-with-repeat` at the very end with `call-interactively`.

**Comment by ninrod** [comment]
Hi @braham-snyder. I suspect that the package is not ready for such a rebind, mainly because of this [line]. the `y` part of `ys` seems rather hardcoded, and this code is the code that seems to be handling the repetition part. 

Thoughts?

**Comment by braham-snyder** [comment]
to those using the workaround: I forgot you'll also want to modify `evil-Surround-edit` the same way

@ninrod that's what I thought from a brief look as well--I was hoping I could just check if `operation` is `yank` (vs. `nil`), but IIRC it never was, even with, e.g., `ys`

the workaround above seems to suffice for me, but I'll update this issue if I encounter problems with it

**Comment by ninrod** [comment]
Ok, but I don't think I follow. Can you post the diff?

**Comment by braham-snyder** [comment]
```From bef952f28920a76cdcde0b5a4f04fd070ae0cad6 Mon Sep 17 00:00:00 2001
From: braham <braham.snyder@gmail.com>
Date: Thu, 19 Jan 2017 18:53:20 -0600
Subject: [PATCH] Workaround fix for `evil-repeat` w/ `evil-surround-edit` on
 one key

This is a workaround to prevent one-key bindings to
`evil-surround-edit` and `evil-Surround-edit` from `evil-repeat`ing
as surrounding with "i" or "a" depending on whether an inner-textobj
or outer-textobj was used. For example, with `r` set to
`evil-surround`, `riw(.` on "word" gave "i(word)i" instead of
"((word))".
---
 evil-surround.el | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/evil-surround.el b/evil-surround.el
index 98b1837..1066062 100644
--- a/evil-surround.el
+++ b/evil-surround.el
@@ -263,7 +263,7 @@ Otherwise call `evil-surround-region'."
     (call-interactively 'evil-surround-delete))
    (t
     (evil-surround-setup-surround-line-operators)
-    (evil-surround-call-with-repeat 'evil-surround-region))))
+    (call-interactively 'evil-surround-region))))
 
 (evil-define-command evil-Surround-edit (operation)
   "Like evil-surround-edit, but for surrounding with additional new-lines.
@@ -276,7 +276,7 @@ It does nothing for change / delete."
    ((eq operation 'delete) nil)
    (t
     (evil-surround-setup-surround-line-operators)
-    (evil-surround-call-with-repeat 'evil-Surround-region))))
+    (call-interactively 'evil-Surround-region))))
 
 (evil-define-operator evil-surround-region (beg end type char &optional force-new-line)
   "Surround BEG and END with CHAR.
-- 
2.11.0
```

**Comment by ninrod** [comment]
@braham-snyder, if I understand correctly, you are loosing the ability to repeat the operation, right? 

because that would be the whole point of the `evil-surround-call-with-repeat`, right? Or am I missing something?

**Comment by braham-snyder** [comment]
correct

**Comment by ninrod** [comment]
@braham-snyder, try looking at [here](https://github.com/timcharper/evil-surround/blob/master/evil-surround.el#L262-L269). I think you'll have to disable the [evil-interactive-setup](https://github.com/timcharper/evil-surround/blob/master/evil-surround.el#L260) function from getting called. that must be screwing the surround mechanism.

**Comment by ninrod** [comment]
@braham-snyder, the `y` starting letter of the surround command is somewhat hard-coded inside evil-surround as far as the repeating mechanism goes, as you can see in this [line](https://github.com/emacs-evil/evil-surround/blob/master/evil-surround.el#L250). 

I do not have the elisp knowledge yet to make this generic easily, but you are welcome to reboot this as a pull request alongside some tests to exercise your use case.
